import { test, expect, Locator, Page } from '@playwright/test';
import * as path from 'path';

export class InsertNewAsset {
    page: Page;
    newAssetPage: Locator;
    addNewAsset: Locator;
    skeleton: Locator;
    selectProject: Locator;
    searchButton: Locator;
    searchByChar: Locator;
    rentalPrice: Locator;
    areaSize: Locator;
    buildingNo: Locator;
    floorNo: Locator;
    roomNo: Locator;
    uploadImage: Locator;
    selectOwner: Locator;
    searchOwnername: Locator;
    addOwnerContact: Locator;
    checkboxFacebook: Locator;
    inputFacebookPage: Locator;
    checkboxLineOA: Locator;
    inputLineOAPage: Locator;
    autoGenerateDetails: Locator;
    createAsset: Locator;

    constructor(page: Page) {
        this.page = page;
        this.newAssetPage = page.getByRole('link', { name: 'ทรัพย์ทั้งหมด' });
        this.addNewAsset = page.getByRole('link', { name: 'เพิ่มทรัพย์ใหม่' });
        this.skeleton = page.locator(".skeleton");
        this.selectProject = page.getByRole("button", { name: "เลือกโครงการ" });
        this.searchButton = page.getByPlaceholder("ค้นหาชื่อโครงการ, ทำเล...");
        this.searchByChar = page.getByRole("button", { name: "Bliss" });
        this.rentalPrice = page.getByPlaceholder("15000");
        this.areaSize = page.getByPlaceholder("35");
        this.buildingNo = page.getByPlaceholder("เช่น Tower A");
        this.floorNo = page.locator('input[type="number"][placeholder="เช่น 15"]');
        this.roomNo = page.getByPlaceholder("เช่น 1502");
        this.uploadImage = page.locator('input[type="file"]');
        this.selectOwner = page.getByRole("button", { name: "— เลือกเจ้าของ —" });
        this.searchOwnername = page.getByRole("button", { name: "เดียร์" });
        this.addOwnerContact = page.getByPlaceholder("@thecozykeys");
        this.checkboxFacebook = page.locator('label', { hasText: 'Facebook Page' });
        this.inputFacebookPage = this.checkboxFacebook.locator('xpath=following-sibling::input[@placeholder="URL โพสต์ (ไม่บังคับ)"]');
        this.checkboxLineOA = page.locator('label', { hasText: 'Line OA' });
        this.inputLineOAPage = this.checkboxLineOA.locator('xpath=following-sibling::input[@placeholder="URL โพสต์ (ไม่บังคับ)"]');
        this.autoGenerateDetails = page.getByRole("button", { name: " สร้างอัตโนมัติ" });
        this.createAsset = page.getByRole("button", { name: "เพิ่มทรัพย์" });
    }

    async navigateToNewAssetPage() {
        await this.newAssetPage.click();
    }

    async waitForPageReady() {
        await expect(this.skeleton).toHaveCount(0, {
            timeout: 15000
        });
    }

    async clickAddNewAsset() {
        await this.addNewAsset.click();
    }

    async fillDetailsAsset(){
        await this.selectProject.click();
        await this.searchButton.pressSequentially("Bliss", { delay: 150 });
        await this.searchByChar.click();
        await this.rentalPrice.fill("7500");
        await this.areaSize.fill("35");
        await this.buildingNo.fill("A");
        await this.floorNo.fill("7");
        await this.roomNo.fill("8606");
        await this.uploadImage.setInputFiles(path.join(__dirname, '../ImageForTest/D-Condo-Bliss.png'));
        await this.page.waitForTimeout(3000);
        await this.selectOwner.click();
        await this.searchOwnername.click();
        await this.addOwnerContact.fill("@thecozykeys");
        await this.checkboxFacebook.click();
        await this.inputFacebookPage.fill("https://www.facebook.com/");
        await this.checkboxLineOA.click();
        await this.inputLineOAPage.fill("https://line.me/");
        await this.autoGenerateDetails.click();
        await this.createAsset.click();
    }

}